version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: bogcretu_blablacar
    stdin_open: true
    tty: true

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    container_name: server
    stdin_open: true
    tty: true

  driver:
    build: ./driver
    volumes:
      - ./driver:/usr/src/app
    depends_on:
      - server
    ports:
      - "5001:80"
    container_name: driver
    stdin_open: true
    tty: true

  rider:
    build: ./rider
    volumes:
      - ./rider:/usr/src/app
    depends_on:
      - server
    ports:
      - "5002:80"
    container_name: rider
    stdin_open: true
    tty: true